version: "1.0"
stages:
  - "clone"
  - "settings"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "theBoEffect/ApiCentral"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  settings:
    image: jch254/docker-node-serverless
    title: Build Settings
    working_directory: "${{clone}}"
    commands:
      - yarn
      - yarn run settings

  build:
    image: jch254/docker-node-serverless
    title: Build Angular
    working_directory: "${{clone}}/portal"
    commands:
      - yarn
      - yarn build --prod
      - echo build done

  test:
    image: jch254/docker-node-serverless
    title: Test Service
    working_directory: "${{clone}}"
    commands:
      - echo starting test
      - yarn test